pipelines:
  default:
    - step:
        image: rooterdev/rspec_ruby2.7.2
        caches:
          - bundler
        script:
          - apt-get install shared-mime-info
          - gem install bundler -v 2.1.4
          - bundle update mimemagic
          - bundle _2.1.4_ install --path .bundle
          - docker run --name mysql-server -v $BITBUCKET_CLONE_DIR/conf.d:/etc/mysql/conf.d/ -e MYSQL_DATABASE=snscrawl_test -e MYSQL_ROOT_PASSWORD=snscrawl_test! -e MYSQL_USER=snscrawl_test -e MYSQL_PASSWORD=snscrawl_test! -d -p 3306:3306 kazaoki/mariadb-mroonga:10.4
          - sleep 30
          - docker exec mysql-server /bin/bash -c "mysql -u root -psnscrawl_test! -h 127.0.0.1 -P 3306 -e "\""SHOW variables LIKE '%ft_min_%'; SHOW variables LIKE 'innodb_ft_enable_stopword';"\"""
          - yarn install
          - bundle exec rake webpacker:compile RAILS_ENV=test
          - bundle exec rails db:setup RAILS_ENV=test DB_PORT=3306 DB_USERNAME=snscrawl_test DB_PASSWORD=snscrawl_test!
          - bundle exec rake db:migrate RAILS_ENV=test DB_PORT=3306 DB_USERNAME=snscrawl_test DB_PASSWORD=snscrawl_test!
          - DB_PORT=3306 DB_USERNAME=snscrawl_test DB_PASSWORD=snscrawl_test! bundle exec rspec
        services:
          - docker
definitions:
  caches:
    bundler: .bundle
