version: 2
jobs:
  build:
    working_directory: ~/linstalizer
    docker:
      - image: rooterdev/rspec_ruby2.7.2
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: kazaoki/mariadb-mroonga:10.4
        environment:
          MYSQL_DATABASE: 'linstalizer_test'
          MYSQL_PASSWORD: 'test'
          MYSQL_ROOT_PASSWORD: 'test'
    steps:
      - checkout
      - restore_cache:
          keys:
            - linstalizer-bundle-v1-{{ checksum "Gemfile.lock" }}
            - linstalizer-bundle-v1-
      - run:
          name: Bundlerをインストール
          command: gem install bundler -v 2.1.4
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install
      - save_cache:
          key: linstalizer-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - linstalizer-yarn-{{ checksum "yarn.lock" }}
            - linstalizer-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: linstalizer-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: DBの待機
          command: sleep 30
      - run:
          name: DBのセットアップ
          command: bundle exec rails db:setup DB_HOST=127.0.0.1
      - run:
          name: webpackerによるコンパイル実行
          command: bundle exec rake webpacker:compile
      - run:
          name: RSpecの実行
          command: DB_HOST=127.0.0.1 bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
